name = "drivelight-worker"
type = "javascript"
# wranglers does not support webpack 5
# type = "webpack" 
# webpack_config = "webpack.config.js"

route = ''
zone_id = ''
workers_dev = true
# usage_model = ''
compatibility_date = "2021-11-28"
# compatibility_flags = []

# KV Store
# Replace the following id , preview_id with your own KV Store
# Below placeholder values wont be replaced by wranger and need to set manually 
kv_namespaces = [{ binding = "driveFileIDKV", id = "", preview_id = "" }]

[build]
command = "npm run build"
# command = "npm install && npm run build"
[build.upload]
format = "service-worker"

# Secrets , Need to be directly set in CF dashboard or with wrangler secret put <NAME>
# [secrets]
# ROOTFOLDERID
# TEAMDRIVEID
# GAPIKEY
# GAPIREFERER
