name = "drivelight-worker"
type = "javascript"
# wranglers does not support webpack 5
# type = "webpack" 
# webpack_config = "webpack.config.js"

account_id = ''
zone_id = ''
# usage_model = ''
compatibility_date = "2021-11-28"
# compatibility_flags = []

[build]
command = "npm run build"
# command = "npm install && npm run build"
[build.upload]
format = "service-worker"

# ENV VARIABLES, will be accessible in the worker
# These are unencrypted and will be visible on git commits
# Not inherited , need to be set indivisually for each environment
# [vars]
# CACHEMAXAGE = "3600"

# Secrets , Need to be directly set in CF dashboard
# [secrets]
# ROOTFOLDERID
# TEAMDRIVEID
# GAPIKEY
# GAPIREFERER

# Environments
# Default environment
workers_dev = true
# KV Store
# Replace the following id , preview_id with your own KV Store
# Below placeholder values wont be replaced by wranger and need to set manually 
kv_namespaces = [{ binding = "driveFileIDKV", id = "", preview_id = "" }]
vars = { CACHEMAXAGE = "3600" }
